from django.contrib.gis import admin

from osm import models

# Register your models here.
admin.site.register(models.AerodromesPoint)
admin.site.register(models.AerodromesPolygon)
admin.site.register(models.AllRoads)
admin.site.register(models.Banks)
admin.site.register(models.Buildings)
admin.site.register(models.Cities)
admin.site.register(models.Farms)
admin.site.register(models.Forest)
admin.site.register(models.Grassland)
admin.site.register(models.Hamlets)
admin.site.register(models.Helipads)
admin.site.register(models.Hotels)
admin.site.register(models.IdpCamps)
admin.site.register(models.Lakes)
admin.site.register(models.MainRoads)
admin.site.register(models.MedicalPoint)
admin.site.register(models.MedicalPolygon)
admin.site.register(models.Military)
admin.site.register(models.Neighborhoods)
admin.site.register(models.Orchards)
admin.site.register(models.Paths)
admin.site.register(models.Placenames)
admin.site.register(models.PoliceStations)
admin.site.register(models.Residential)
admin.site.register(models.Restaurants)
admin.site.register(models.Riverbanks)
admin.site.register(models.Rivers)
admin.site.register(models.SchoolsPoint)
admin.site.register(models.SchoolsPolygon)
admin.site.register(models.SpatialRefSys)
admin.site.register(models.Tracks)
admin.site.register(models.TrainStations)
admin.site.register(models.VillageGreen)
admin.site.register(models.Villages)
